SELECT EMP_ID , EMP_NAME , SALARY , HIRE_DATE FROM EMPLOYEE;

-- 300만 이상
SELECT EMP_ID , EMP_NAME , JOB_CODE , HIRE_DATE 
FROM EMPLOYEE
WHERE SALARY >= 3000000
ORDER BY SALARY DESC;

/* 부서명을 입력 받아 해당 부서에 존재하는 사원의 
 * 사번, 이름, 급여, 부서명을 사번 오름차순으로 조회 */
SELECT EMP_ID, EMP_NAME, SALARY, DEPT_TITLE 
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE DEPT_TITLE ='총무부'
ORDER BY EMP_ID;

-- SQL을 바꾸는 방법
SELECT * FROM (
   SELECT EMP_ID, EMP_NAME, SALARY, NVL(DEPT_TITLE, 'null') DEPT_TITLE
   FROM EMPLOYEE 
   LEFT JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
   ORDER BY EMP_ID )
WHERE DEPT_TITLE = 'null';

SELECT NVL(DEPT_TITLE,'부서없음') , JOB_NAME, EMP_NAME , EMAIL
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE =  DEPT_ID)
JOIN JOB USING (JOB_CODE);

SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE,'없음') DEPT_TITLE, JOB_NAME, NVL(PHONE,'없음') PHONE
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE EMP_ID = 200
;

SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE,'없음') DEPT_TITLE, JOB_NAME, NVL(PHONE,'없음') PHONE
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE EMP_NAME LIKE '%동%'
;

SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE,'없음') DEPT_TITLE, JOB_NAME, NVL(PHONE,'없음') PHONE
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE SALARY BETWEEN 3000000 AND 4000000
;

SELECT EMP_ID, EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE SALARY BETWEEN 2000000 AND 3000000
ORDER BY SALARY DESC
;

-- 사번 생성 시퀀스(223번 시작)
CREATE SEQUENCE SEQ_EMP_ID
START WITH 223 -- 223번 시작
INCREMENT BY 1 -- 1씩 증가
NOCYCLE -- 반복 없음
NOCACHE; -- 미리 만들어 두는 번호 없음

-- SEQ_EMP_ID.NEXTVAL : 다음 번호 생성
-- SEQ_EMP_ID.CURRVAL : 현재 번호 조회

UPDATE 테이블명
SET 컬럼명 = 수정할 값,
	컬럼명 = 수정할 값,
	컬럼명 = 수정할 값
WHERE 조건;

UPDATE EMPLOYEE
SET EMAIL = ?,
	PHONE = ?,
	SALARY = ?
WHERE EMP_ID = ?
;

SELECT EMP_ID , EMP_NAME , PHONE , EMAIL , SALARY FROM EMPLOYEE
WHERE EMP_ID = 223; 

SELECT EMP_ID, EMP_NAME, ENT_YN, ENT_DATE 
FROM EMPLOYEE 
WHERE EMP_ID = ?;

UPDATE EMPLOYEE
SET ENT_YN = 'N',
	ENT_DATE = SYSDATE 
WHERE EMP_ID = 223
;

SELECT ENT_YN,ENT_DATE 
FROM EMPLOYEE
WHERE EMP_ID = 223;

ROLLBACK;