-- 1번
SELECT STUDENT_NO "학번", STUDENT_NAME "이름",
TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD')  "입학년도"
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
WHERE DEPARTMENT_NO ='002'
ORDER BY ENTRANCE_DATE;

-- 2번
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) !=3;

-- 3번
SELECT PROFESSOR_NAME, PROFESSOR_SSN , 
FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6)))/12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1)='1'
ORDER BY 나이;

-- 4번
-- SELECT TRIM(LEADING SUBSTR(PROFESSOR_NAME,1,1) FROM PROFESSOR_NAME) 이름
SELECT  SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;

-- 5번
SELECT STUDENT_NO , STUDENT_NAME
FROM TB_STUDENT
WHERE FLOOR(MONTHS_BETWEEN(ENTRANCE_DATE,TO_DATE('19'||SUBSTR(STUDENT_SSN,1,6)))/12)=19;

-- 6번
SELECT TO_CHAR(TO_DATE(20201225),'DAY') FROM DUAL; -- 금요일

-- 7번
--TO_DATE('99/10/11','YY/MM/DD')
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;

-- 8번
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE NOT STUDENT_NO LIKE 'A%';

-- 9번
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10번
SELECT DEPARTMENT_NO "학과번호" , COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY "학과번호";

-- 11번
SELECT COUNT(*) 
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12번
SELECT SUBSTR(TERM_NO,1,4) "년도", ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY "년도"; 

-- 13번
SELECT DEPARTMENT_NO 학과코드명,
COUNT(DECODE(ABSENCE_YN,'Y','0')) "휴학생 수" 
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


-- 14번
SELECT DISTINCT STUDENT_NAME "동일이름", COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*)>1
ORDER BY STUDENT_NAME;

					 
-- 15번
SELECT SUBSTR(TERM_NO,1,4) "년도", SUBSTR(TERM_NO,5,2) "학기" ,
ROUND(AVG(POINT),1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2));

